import type {
  Track,
  VideoTemplate,
  Project,
  PricingPlan,
  UserProfile,
} from "@musicmotion/shared";

export const MOCK_TRACKS: Track[] = [
  {
    id: "track-1",
    provider: "jamendo",
    externalId: "jm-101",
    title: "Cyberpunk Horizon",
    artist: "Alex Stoner",
    album: "Neon Echoes",
    duration: 184,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/101/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    bpm: 128,
    tags: ["Synthwave", "Cyberpunk", "Driving", "Bass"],
    license: {
      type: "Creative Commons BY 4.0",
      url: "https://creativecommons.org/licenses/by/4.0/",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
  {
    id: "track-2",
    provider: "jamendo",
    externalId: "jm-102",
    title: "Midnight Coffee & Lo-Fi",
    artist: "Luna Beats",
    album: "Study Session Vol. 3",
    duration: 142,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/102/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80",
    bpm: 84,
    tags: ["Lo-Fi", "Chillhop", "Cozy", "Piano"],
    license: {
      type: "Creative Commons BY 4.0",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
  {
    id: "track-3",
    provider: "jamendo",
    externalId: "jm-103",
    title: "Valhalla Awakening",
    artist: "Nordic Symphony",
    album: "Cinematic Realms",
    duration: 215,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/103/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80",
    bpm: 140,
    tags: ["Cinematic", "Orchestral", "Epic", "Trailer"],
    license: {
      type: "Creative Commons BY-SA 4.0",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
  {
    id: "track-4",
    provider: "jamendo",
    externalId: "jm-104",
    title: "Tokyo Underground Trap",
    artist: "KAIZO",
    album: "Shibuya Nights",
    duration: 168,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/104/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=400&q=80",
    bpm: 145,
    tags: ["Trap", "Hip Hop", "808", "Dark"],
    license: {
      type: "Creative Commons BY 4.0",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
  {
    id: "track-5",
    provider: "jamendo",
    externalId: "jm-105",
    title: "Solaris Dreamscape",
    artist: "Aetheria",
    album: "Cosmic Odyssey",
    duration: 198,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/105/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    bpm: 110,
    tags: ["Ambient", "Dreamy", "Space", "Ethereal"],
    license: {
      type: "Creative Commons BY 4.0",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
  {
    id: "track-6",
    provider: "jamendo",
    externalId: "jm-106",
    title: "Festival Drop 2026",
    artist: "Vortex DJ",
    album: "Mainstage Euphoria",
    duration: 190,
    audioUrl: "https://prod-1.storage.jamendo.com/download/track/106/mp32/",
    coverArtUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=400&q=80",
    bpm: 132,
    tags: ["EDM", "House", "Festival", "Energetic"],
    license: {
      type: "Creative Commons BY 4.0",
      attributionRequired: true,
      commercialAllowed: true,
    },
  },
];

export const MOCK_GENRES = [
  { id: "synthwave", name: "Synthwave / Cyber", count: "1,240 tracks", gradient: "from-fuchsia-600 via-pink-600 to-rose-600" },
  { id: "lofi", name: "Lo-Fi & Chillhop", count: "2,890 tracks", gradient: "from-amber-500 via-orange-500 to-rose-500" },
  { id: "cinematic", name: "Cinematic & Trailer", count: "980 tracks", gradient: "from-blue-600 via-indigo-600 to-violet-700" },
  { id: "hiphop", name: "Trap & Hip Hop", count: "3,120 tracks", gradient: "from-purple-600 via-violet-700 to-indigo-900" },
  { id: "edm", name: "EDM & Club Beats", count: "1,850 tracks", gradient: "from-emerald-500 via-teal-600 to-cyan-700" },
  { id: "ambient", name: "Ambient & Meditation", count: "740 tracks", gradient: "from-teal-500 via-blue-600 to-purple-600" },
  { id: "rock", name: "Indie Rock & Pop", count: "1,410 tracks", gradient: "from-rose-500 via-red-600 to-amber-600" },
  { id: "classical", name: "Neo-Classical Piano", count: "620 tracks", gradient: "from-neutral-700 via-slate-800 to-zinc-900" },
];

export const MOCK_TEMPLATES: VideoTemplate[] = [
  {
    id: "tpl-1",
    title: "Neon Cyberpunk Anthem",
    description: "Fast-paced visual cuts with glitch transitions and neon pop typography.",
    category: "reels",
    thumbnailUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80",
    scenesCount: 5,
    defaultDuration: 15,
    visualStyle: "Cinematic",
    aspectRatio: "9:16",
    musicGenre: "Synthwave",
    tags: ["Trending", "TikTok", "Reels", "Glitch"],
    rating: 4.9,
    downloadsCount: 14200,
    isTrending: true,
  },
  {
    id: "tpl-2",
    title: "Midnight Lo-Fi Lyrics",
    description: "Cozy pastel aesthetic with smooth karaoke text highlights and slow zoom motions.",
    category: "lyrics",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    scenesCount: 3,
    defaultDuration: 20,
    visualStyle: "Anime",
    aspectRatio: "9:16",
    musicGenre: "Lo-Fi",
    tags: ["Lyrics", "Cozy", "Karaoke", "Lo-Fi"],
    rating: 4.8,
    downloadsCount: 9800,
    isTrending: true,
  },
  {
    id: "tpl-3",
    title: "Pulse Waveform Visualizer",
    description: "Dynamic circular audio reactor with reactive particles and heavy bass drops.",
    category: "visualizer",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80",
    scenesCount: 4,
    defaultDuration: 30,
    visualStyle: "Dark",
    aspectRatio: "9:16",
    musicGenre: "EDM",
    tags: ["Visualizer", "Bass", "EDM", "Reactor"],
    rating: 4.7,
    downloadsCount: 6500,
  },
  {
    id: "tpl-4",
    title: "Cinematic Trailer Teaser",
    description: "Dramatic cinematic lighting with deep fades, orchestral sync, and widescreen bars.",
    category: "cinematic",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    scenesCount: 6,
    defaultDuration: 25,
    visualStyle: "Realistic",
    aspectRatio: "9:16",
    musicGenre: "Cinematic",
    tags: ["Trailer", "Movie", "Epic", "Cinematic"],
    rating: 4.95,
    downloadsCount: 18900,
    isTrending: true,
  },
  {
    id: "tpl-5",
    title: "Podcast Viral Hook",
    description: "High-contrast subtitle cards designed to stop the scroll on Instagram and TikTok.",
    category: "podcast",
    thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=600&q=80",
    scenesCount: 2,
    defaultDuration: 15,
    visualStyle: "Minimal",
    aspectRatio: "9:16",
    musicGenre: "Acoustic",
    tags: ["Podcast", "Talk", "Subtitles", "Viral"],
    rating: 4.6,
    downloadsCount: 5200,
  },
  {
    id: "tpl-6",
    title: "Dreamy Ethereal Aura",
    description: "Soft fantasy visuals with floating clouds, glowing runes, and ambient transitions.",
    category: "lofi",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    scenesCount: 4,
    defaultDuration: 18,
    visualStyle: "Dreamy",
    aspectRatio: "9:16",
    musicGenre: "Ambient",
    tags: ["Fantasy", "Dreamy", "Glow", "Aura"],
    rating: 4.85,
    downloadsCount: 7100,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-101",
    title: "Tokyo Cyberpunk Night Drive",
    status: "completed",
    locale: "en",
    trackSelection: {
      id: "sel-1",
      projectId: "proj-101",
      trackId: "track-1",
      track: MOCK_TRACKS[0],
      startTime: 15,
      endTime: 30,
    },
    captions: [
      {
        id: "cap-1",
        projectId: "proj-101",
        startTime: 0,
        endTime: 4,
        text: "LIGHTS FLASH ACROSS THE GRID ⚡",
        style: { position: "bottom", animation: "pop", fontSize: 44, textColor: "#ffffff" },
      },
      {
        id: "cap-2",
        projectId: "proj-101",
        startTime: 5,
        endTime: 9,
        text: "SPEED OF SOUND IN THE NIGHT",
        style: { position: "bottom", animation: "pop", fontSize: 44, textColor: "#f43f5e" },
      },
    ],
    scenes: [
      {
        id: "sc-1",
        projectId: "proj-101",
        prompt: "Futuristic highway with neon hypercars under rain, 8k vertical render",
        visualStyle: "Cinematic",
        imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
        order: 0,
        duration: 5,
        status: "completed",
      },
      {
        id: "sc-2",
        projectId: "proj-101",
        prompt: "Cyberpunk rider looking at holographic city skyscraper skyline",
        visualStyle: "Cinematic",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80",
        order: 1,
        duration: 5,
        status: "completed",
      },
    ],
    videoConfig: {
      width: 1080,
      height: 1920,
      fps: 30,
      aspectRatio: "9:16",
      duration: 15,
      resolution: "1080p",
      codec: "h264",
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    outputVideoUrl: "https://example.com/renders/tokyo-drive.mp4",
    createdAt: "2026-08-20T14:30:00Z",
    updatedAt: "2026-08-21T18:10:00Z",
  },
  {
    id: "proj-102",
    title: "Midnight Study Session Reel",
    status: "ready",
    locale: "en",
    trackSelection: {
      id: "sel-2",
      projectId: "proj-102",
      trackId: "track-2",
      track: MOCK_TRACKS[1],
      startTime: 0,
      endTime: 20,
    },
    captions: [
      {
        id: "cap-3",
        projectId: "proj-102",
        startTime: 0,
        endTime: 6,
        text: "Just you, your thoughts, and the rain ☕",
        style: { position: "center", animation: "fade", fontSize: 40, textColor: "#fed7aa" },
      },
    ],
    scenes: [
      {
        id: "sc-3",
        projectId: "proj-102",
        prompt: "Warm lit cozy room with rain droplets on window, lo-fi aesthetic",
        visualStyle: "Anime",
        imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
        order: 0,
        duration: 7,
        status: "completed",
      },
    ],
    videoConfig: {
      width: 1080,
      height: 1920,
      fps: 30,
      aspectRatio: "9:16",
      duration: 20,
      resolution: "1080p",
      codec: "h264",
    },
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    createdAt: "2026-08-21T09:15:00Z",
    updatedAt: "2026-08-22T11:00:00Z",
  },
];

export const MOCK_PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free Starter",
    description: "Try out MusicMotion with essential features and free Jamendo music access.",
    priceMonthly: 0,
    priceAnnualMonthly: 0,
    creditsMonthly: 30,
    features: [
      "30 AI scene credits / month",
      "720p HD video exports",
      "Licensed Jamendo music catalog",
      "WaveSurfer audio trimming",
      "Standard caption animations",
      "Watermarked exports",
    ],
    ctaText: "Start for Free",
  },
  {
    id: "creator",
    name: "Creator Pro",
    description: "Designed for content creators, influencers, and artists posting daily viral videos.",
    priceMonthly: 29,
    priceAnnualMonthly: 23,
    creditsMonthly: 300,
    isPopular: true,
    features: [
      "300 AI scene credits / month",
      "1080p 60FPS Full HD exports",
      "No MusicMotion watermark",
      "All 9 AI visual style presets",
      "Full Jamendo commercial licensing",
      "Custom audio file uploads",
      "Fast cloud render queue priority",
      "Export directly to TikTok & Reels",
    ],
    ctaText: "Upgrade to Creator Pro",
  },
  {
    id: "studio",
    name: "Studio Enterprise",
    description: "High-volume media agencies, music labels, and production teams needing 4K video.",
    priceMonthly: 89,
    priceAnnualMonthly: 71,
    creditsMonthly: 1200,
    features: [
      "1,200 AI scene credits / month",
      "Ultra HD 4K 60FPS video rendering",
      "Custom brand typography & watermarks",
      "Multi-seat team workspace",
      "Dedicated BullMQ render node",
      "Custom AI model fine-tuning",
      "Direct API access",
      "24/7 dedicated support SLA",
    ],
    ctaText: "Contact Studio Team",
  },
];

export const MOCK_USER: UserProfile = {
  id: "user-123",
  name: "Alex Vance",
  email: "alex.vance@creator.io",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
  tier: "creator",
  creditsTotal: 300,
  creditsRemaining: 185,
  storageUsedBytes: 4294967296, // 4 GB
  storageLimitBytes: 21474836480, // 20 GB
  createdAt: "2026-01-15T00:00:00Z",
};

export const MOCK_ARTISTS = [
  {
    id: "art-1",
    name: "Alex Stoner",
    genre: "Synthwave / Cyber",
    monthlyListeners: "245K",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    tracksCount: 18,
  },
  {
    id: "art-2",
    name: "Luna Beats",
    genre: "Lo-Fi & Chillhop",
    monthlyListeners: "480K",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    tracksCount: 32,
  },
  {
    id: "art-3",
    name: "Nordic Symphony",
    genre: "Cinematic & Trailer",
    monthlyListeners: "190K",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    tracksCount: 14,
  },
  {
    id: "art-4",
    name: "KAIZO",
    genre: "Trap & Hip Hop",
    monthlyListeners: "360K",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    tracksCount: 22,
  },
  {
    id: "art-5",
    name: "Aetheria",
    genre: "Ambient & Space",
    monthlyListeners: "125K",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    tracksCount: 16,
  },
  {
    id: "art-6",
    name: "Vortex DJ",
    genre: "EDM & Festival",
    monthlyListeners: "510K",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80",
    tracksCount: 28,
  },
];

export const MOCK_ALBUMS = [
  {
    id: "alb-1",
    title: "Neon Echoes (Deluxe)",
    artist: "Alex Stoner",
    tracksCount: 10,
    coverArtUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    releaseYear: 2026,
    genre: "Synthwave",
  },
  {
    id: "alb-2",
    title: "Study Session Vol. 3",
    artist: "Luna Beats",
    tracksCount: 14,
    coverArtUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80",
    releaseYear: 2025,
    genre: "Lo-Fi",
  },
  {
    id: "alb-3",
    title: "Cinematic Realms Soundtrack",
    artist: "Nordic Symphony",
    tracksCount: 8,
    coverArtUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80",
    releaseYear: 2026,
    genre: "Cinematic",
  },
  {
    id: "alb-4",
    title: "Shibuya Underground",
    artist: "KAIZO",
    tracksCount: 12,
    coverArtUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=400&q=80",
    releaseYear: 2026,
    genre: "Hip Hop",
  },
];

export const MOCK_TESTIMONIALS = [
  {
    quote: "MusicMotion cut my Reels creation time from 4 hours in Premiere to 3 minutes. The AI visual scenes match the music drops perfectly.",
    author: "Sarah Jenkins",
    handle: "@sarahcreates",
    role: "TikTok Creator • 1.2M Followers",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
  },
  {
    quote: "The licensed music catalog means I never get copyright strikes. The waveform trimmer and animated captions make lyric videos effortless.",
    author: "Marcus Chen",
    handle: "@marcusbeats",
    role: "Independent Music Producer",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
  },
  {
    quote: "RTL Arabic support and sleek dark mode make this the best creative studio in our agency stack. Remotion exports are flawlessly crisp.",
    author: "Tariq Al-Mansoor",
    handle: "@tariq_agency",
    role: "Digital Media Director",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
  },
];


